# Spring properties
spring:
  application:
     name: dog-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

# HTTP Server
server:
  port: 8084   # HTTP (Tomcat) port